# Generated by Django 3.0.5 on 2020-05-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_publiacion',
            new_name='fecha_publicacion',
        ),
    ]
