# Generated by Django 3.0.5 on 2020-05-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0002_auto_20200502_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
