# Generated by Django 3.0.5 on 2020-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0004_auto_20200503_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark', models.BooleanField(default=False)),
            ],
        ),
    ]
