# Generated by Django 3.0.5 on 2020-05-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0005_colortheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorTheme',
        ),
    ]
