# Generated by Django 3.0.5 on 2020-05-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0008_auto_20200509_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fehca_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(),
        ),
    ]
