# Generated by Django 3.0.5 on 2020-05-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0010_auto_20200509_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dierccion', models.EmailField(max_length=254)),
            ],
        ),
    ]
